### ISSUE TITLE
Error: Invalid redirect URI

### ISSUE THREAD

**Issue by LutherTS** [workos/next-authkit-example#6]
When I click on the Sign In button I get redirected to a page that says the above message with the following: 

> Make sure that the app uses the correct redirect URI. If you are not sure what this means, please contact your organization admin.

Can you explain what could potentially be going wrong?

**Comment by andy-hook** [comment]
@LutherTS – have you [configured a redirect uri](https://workos.com/docs/user-management/1-configure-your-project/configure-a-redirect-uri) in your dashboard? it should be set to `http://localhost:3000/callback`. If so, double check the protocol is using `http` per your local environment.

**Comment by LutherTS** [comment]
@andy-hook I didn't configure the redirect URI before, thanks for guiding me. 

~~Now that I did, I'm getting a different, general error:~~ 

> Error
Something went wrong
Couldn’t sign in. If you are not sure what happened, please contact your organization admin.

~~I think this is due to an error I'm seeing in auth.ts at the following code on `redirectUri`:~~
```
const authorizationUrl = workos.userManagement.getAuthorizationUrl({
    provider: "authkit",
    clientId: getClientId(),
    // The endpoint that WorkOS will redirect to after a user authenticates
    redirectUri,
  });
```
~~Here's the error:~~ 
> Object literal may only specify known properties, but 'redirectUri' does not exist in type 'AuthorizationURLOptions'.~~

I just made a pull request to fix it. Now I'm seeing the sign up form. Thank you.

**Comment by andy-hook** [comment]
Glad you have things working! we'll update the readme to make the redirect instructions clearer. Thanks for raising the PR, will follow up with a comment there.
